export enum InternalEvent {
    AcquirersOfferRequestHasDeleted = 'acquirers-offer-request-has-deleted',
    AcquirersSharingStatus = 'acquirers-sharing-status',
    AcquirersSigningStatus = 'acquirers-signing-status',

    AuthCreateOrUpdateUserProfile = 'auth-create-or-update-user-profile',
    AuthAssignUserToPushToken = 'auth-assign-user-to-push-token',
    AuthUserLogOut = 'auth-user-log-out',

    AuthCreateOrUpdateEResidentProfile = 'auth-create-or-update-eresident-profile',
    AuthAssignEResidentToPushToken = 'auth-assign-eresident-to-push-token',
    AuthEResidentLogOut = 'auth-eresident-log-out',

    AuthCreateOrUpdateCabinetUserProfile = 'auth-create-or-update-cabinet-profile',

    DocumentsAddDocumentInProfile = 'documents-add-document-in-profile',
    DocumentsAddDocumentsInProfile = 'documents-add-documents-in-profile',
    DocumentsAddDocumentPhoto = 'documents-add-document-photo',
    DocumentsRemoveDocumentPhoto = 'documents-remove-document-photo',
    DocumentsObtainedVehicleLicense = 'documents.obtained.vehicle-license',
    DocumentsObtainedRefInternallyDisplacedPerson = 'documents.obtained.reference-internally-displaced-person',
    DocumentsAdultRegistrationAddressCommunity = 'documents-adult-registration-address-community',

    GatewayUserActivity = 'gateway-user-activity',

    PaymentCallbackStatus = 'payment-callback-status',
    PaymentCallbackStatusV2 = 'payment-callback-status-v2',
    PaymentExecuted = 'payment-executed',
    PaymentExpired = 'payment-expired',

    PublicServicePenaltyCreated = 'public-service-penalty-created',
    PublicServiceReceivedOpenedDebt = 'public-service-received-opened-debt',
    PublicServiceReceivedEnforcedDebt = 'public-service-received-enforced-debt',
    PublicServiceSigningStatus = 'public-service-signing-status',
    PublicServiceCriminalCertificateStatusUpdated = 'public-service-criminal-certificate-status-updated',

    UserPenaltyIdentified = 'user-penalty-identified',
    UserSendMassNotifications = 'user-send-mass-notifications',
    UserSendMassAnonymousNotifications = 'user-send-mass-anonymous-notifications',
    UserSendMassSilentPushes = 'user-send-mass-silent-pushes',
    UserProfileCreated = 'user-profile-created',

    NotificationPenaltyCreated = 'notification-penalty-created',
    NotificationOpenedDebtCreated = 'notification-opened-debt-created',
    NotificationEnforcedDebtCreated = 'notification-enforced-debt-created',
    NotificationHasRead = 'notification-has-read',
    NotificationHasDeleted = 'notification-has-deleted',

    RateService = 'rate-service',
    RatingSaved = 'rating-saved',

    DocumentDeliveryCallbackStatus = 'document-delivery-callback-status',

    CriminalCertificateStatusUpdated = 'criminal-certificate-status-updated',
}

export enum ScheduledTaskEvent {
    AuthCheckRefreshTokensExpiration = 'auth-check-refresh-tokens-expiration',

    DamagedPropertyNotifyRepairMessageAwaiting = 'damaged-property-notify-repair-message-awaiting',

    DepositGuaranteePaymentsLoadCompensationDeposits = 'deposit-guarantee-payments-load-compensation-deposits',

    DocumentAcquirersRefreshOfferRequests = 'document-acquirers-refresh-offer-requests',

    DocumentsArchiveUsedOtp = 'documents-archive-used-otp',
    DocumentsDeleteUnusedOtp = 'documents-delete-unused-otp',
    DocumentsDeleteTaxpayerApplications = 'documents-delete-taxpayer-applications',

    AuthUpdateBankIdBankList = 'auth-update-bank-id-bank-list',

    PublicServiceCheckApplications = 'public-service-check-applications',
    PublicServiceLoadPenalties = 'public-service-load-penalties',
    PublicServiceLoadPenaltiesV2 = 'public-service-load-penalties-v2',
    PublicServiceCheckInspectorPenaltiesForDeadline = 'public-service-check-inspector-penalties-for-deadline', // TODO (BACK-782) remove as deprecated
    PublicServiceCheckPenaltiesForDeadline = 'public-service-check-penalties-for-deadline',
    PublicServiceLoadMiaDictionaries = 'public-service-load-mia-dictionaries',
    PublicServiceCheckDriverLicenseReplacementApplications = 'public-service-check-driver-license-replacement-applications',
    PublicServiceCheckDriverLicenseReplacementApplicationsSendExpiration = 'public-service-check-driver-license-replacement-applications-send-expiration',
    PublicServiceDeleteExpiredMassVaccinationTickets = 'public-service-delete-expired-mass-vaccination-tickets',
    PublicServiceRevokeMassVaccination = 'public-service-revoke-mass-vaccination',
    PublicServiceCheckResidenceRegistrations = 'public-service-check-residence-registrations',
    PublicServiceCheckDebtsChanges = 'public-service-check-debts-changes',
    PublicServiceCheckCriminalRecordCertificateApplications = 'public-service-check-criminal-record-certificate-applications',
    PublicServiceCreateVaccinationAidBankReports = 'public-service-create-vaccination-aid-bank-reports',
    PublicServiceCreateMartialLawAidBankReports = 'public-service-create-martial-law-aid-bank-reports',
    PublicServiceCreateVaccinationAidReport = 'public-service-create-vaccination-aid-report',
    PublicServiceCreateVaccinationAidPfuReport = 'public-service-create-vaccination-aid-pfu-report',
    PublicServiceCreateIssuedMortgageReport = 'public-service-create-issued-mortgage-report',
    PublicServiceCheckProperUserApplications = 'public-service-check-proper-user-applications',
    PublicServiceDeleteProperUserExpiredApplications = 'public-service-delete-proper-user-expired-applications',
    PublicServiceCheckUnemploymentStatusApplications = 'public-service-check-unemployment-status-applications',
    PublicServiceCheckUnemploymentStatusCancelingApplications = 'public-service-check-unemployment-status-canceling-applications',
    PublicServiceCheckMilitaryBondsPartners = 'public-service-check-military-bonds-partners',
    PublicServiceUpdateMilitaryBondsOffers = 'public-service-update-military-bonds-offers',
    PublicServiceUpdateMilitaryBondsDictionaries = 'public-service-update-military-bonds-dictionaries',
    PublicServiceDeleteExpiredResidenceCertOrders = 'public-service-delete-expired-residence-cert-orders',
    PublicServiceCheckIsMortgageApplicantHasAcceptedOffer = 'public-service-check-is-mortgage-applicant-has-accepted-offer',
    PublicServiceCheckIsMortgagePartnerHasVerifiedDataRequest = 'public-service-check-is-mortgage-partner-has-verified-data-request',
    PublicServiceUploadLedExchangeOrders = 'public-service-upload-led-exchange-orders',
    PublicServiceCheckLedExchangeReport = 'public-service-check-led-exchange-report',
    PublicServiceUpdateDictionaries = 'public-service-update-dictionaries',
    PublicServiceCreateErecoverySubmissionReport = 'public-service-create-erecovery-submission-report',
    PublicServiceImportErecoveryPfuReport = 'public-service-import-erecovery-pfu-report',
    PublicServiceCheckCourtPenaltiesPaymentTerm = 'public-service-check-court-penalties-payment-term',
    PublicServiceSendNacpDeclarantRelativesDistributions = 'public-service-send-nacp-declarant-relatives-distributions',
    PublicServiceExpireNacpDeclarantRelativesDistributions = 'public-service-expire-nacp-declarant-relatives-distributions',

    CriminalCertCheckCriminalRecordCertificateApplications = 'criminal-cert-check-criminal-record-certificate-applications',

    NotificationSendNewPenalties = 'notification-send-new-penalties',
    NotificationSendDistributions = 'notification-send-distributions',

    UserCheckCovidCertificatesExpirations = 'user-check-covid-certificates-expirations',
    UserCheckDriverLicensesExpirations = 'user-check-driver-licenses-expirations',
    UserCheckVehicleLicensesExpirations = 'user-check-vehicle-licenses-expirations',
    UserCheckDiiaIdExpirations = 'user-check-diiaid-expirations',

    PartnerProcessVaccinationAidAccounts = 'partnerProcessVaccinationAidAccounts',

    PaymentCheckDelayedOrders = 'paymentCheckDelayedOrders',

    AddressServiceUpdateAtu = 'address-service-update-atu',

    DocumentDeliveryCheckExpiredOrders = 'document-delivery-check-expired-orders',

    InvincibilityLoadPoints = 'invincibility-load-points',
    InvincibilityLoadShelters = 'invincibility-load-shelters',
}

export enum ExternalEvent {
    AidVaccinationStatus = 'aid.vaccination.status',

    AttestationGoogleDevice = 'attestation.google.device',
    IntegrityGoogleDevice = 'integrity.google.device',
    AttestationHuaweiDevice = 'attestation.huawei.device',

    UbkiCreditInfo = 'ubki-credit-info',

    DgcValidate = 'dgc.validate',

    DiiaIdCertificateCreate = 'diia-id.certificate.create',
    DiiaIdCertificateRevoke = 'diia-id.certificate.revoke',
    DiiaIdCertificateRevokeAll = 'diia-id.certificate.revoke-all',
    DiiaIdHashFiles = 'diia-id.hash.files',
    DiiaIdSignHashesInit = 'diia-id.sign.hashes.init',
    DiiaIdHashFilesIntegrity = 'diia-id.hash.files-integrity',
    DiiaIdSignDpsPackageInit = 'diia-id.sign.dps.package.init',
    DiiaIdSignDpsPackagePrepare = 'diia-id.sign.dps.package.prepare',
    DiiaIdCertificateInfo = 'diia-id.certificate.info',

    DocumentCovidCertificateProcessing = 'document.covid-certificate.processing',
    DocumentCovidCertificate = 'document.covid-certificate',

    DocumentResidenceCertProcessing = 'document.residence-cert.processing',
    DocumentResidenceCert = 'document.residence-cert',

    EResidentAuthConfirmation = 'eresident.eresident-auth-confirmation',
    EResidentDocuments = 'eresident.eresident-documents',
    EResidentDiiaIdCreation = 'eresident.eresident-diiaid-creation',

    RepoDmsUnitedTerritorialCommunitySendApplicationForRegistrationOfResidence = 'dms.united-territorial-community.application-for-registration-of-residence.send',
    RepoDmsUnitedTerritorialCommunityResultApplicationForRegistrationOfResidence = 'dms.united-territorial-community.application-for-registration-of-residence.result',

    FaceRecoAuthNfcUserPersist = 'auth.nfc.user.persist',
    FaceRecoAuthPhotoVerification = 'auth.photo.verification',
    FaceRecoUserPhotoExtractFeaturePoints = 'user.photo.extract.feature.points',
    FaceRecoUserPhotoMatch = 'user.photo.match',
    AuthSaveNfcScanResult = 'auth.nfc.scan-result',
    AuthGetInnByUnzr = 'auth.nfc.inn-by-unzr',

    NotificationSendEmail = 'notification.email',
    NotificationSendSms = 'notification.sms',
    NotificationSendPush = 'notification.push',
    NotificationPushTopicSubscribe = 'notification.push.topic.subscribe',
    NotificationPushTopicUnsubscribe = 'notification.push.topic.unsubscribe',
    NotificationSend = 'notification.send',
    NotificationSendTarget = 'notification.send.target',
    NotificationTopicSubscribe = 'notification.topic.subscribe',
    NotificationTopicSubscribeTarget = 'notification.topic.subscribe.target',
    NotificationTopicUnsubscribe = 'notification.topic.unsubscribe',

    NotificationTemplateCreate = 'notification.template.create',
    NotificationDistributionCreate = 'notification.distribution.create',
    NotificationDistributionStatus = 'notification.distribution.status',
    NotificationDistributionStatusRecipients = 'notification.distribution.status-recipients',
    NotificationDistributionCancel = 'notification.distribution.cancel',

    RepoDocumentDriverLicense = 'document.driver-license',
    RepoDocumentVehicleLicenses = 'document.vehicle-licenses',
    RepoDocumentVehicleLicenseOwner = 'document.vehicle-license-owner',
    RepoDocumentVehicleLicenseProper = 'document.vehicle-license-proper',
    RepoDocumentVehicleInsurance = 'document.vehicle-insurance',
    RepoDocumentStudentIdCard = 'document.student-id-card',
    RepoDocumentInternalPassport = 'document.internal-passport',
    RepoDocumentForeignPassport = 'document.foreign-passport',
    RepoDocumentPassports = 'document.passports',
    RepoDocumentPassportsByInn = 'document.passports_by_inn',
    RepoDocumentTaxpayerCard = 'document.taxpayer-card',
    RepoDocumentRefInternallyDisplacedPerson = 'document.reference-internally-displaced-person',
    RepoDocumentBirthCertificate = 'document.birth-certificate',
    DocumentEducation = 'document.education',
    RepoDocumentRnokpp = 'document.rnokpp',
    RepoAuthEisAgree = 'eis.agree',
    RepoDocumentPensionCard = 'document.pension-card',
    RepoDocumentCovidCertSign = 'document.covid-cert.sign',
    RepoDocumentCovidCertVerify = 'document.covid-cert.verify',
    RepoDocumentEPermit = 'document.e-permit',

    PrivateEntrepreneurPayerCredentials = 'private-entrepreneur.payer-credentials',
    PrivateEntrepreneurBankAccounts = 'private-entrepreneur.bank-accounts',
    PrivateEntrepreneurTaxAccounts = 'private-entrepreneur.tax-accounts',
    PrivateEntrepreneurBankAccountIncomePeriod = 'private-entrepreneur.bank-account.income-period',
    PrivateEntrepreneurBankAccountReportPeriod = 'private-entrepreneur.bank-account.report-period',
    PrivateEntrepreneurPayerDeclaration = 'private-entrepreneur.payer-declaration',
    PayerIncomeQuery = 'payer.income-q',
    PayerIncomeAnswer = 'payer.income-a',

    PublicServiceDrrpExtSearch = 'public-service.drrp-extsearch',
    PublicServiceDrrpExtGroup = 'public-service.drrp-extgroup',
    PublicServiceDrrpGetActualAtu = 'public-service.drrp-getactualatu',
    PublicServiceDriverLicenseExchangeApplication = 'public-service.driver-license.exchange.application',
    PublicServiceDriverLicenseExchangePayment = 'public-service.driver-license.exchange.payment',
    PublicServiceGetPenaltiesByPeriod = 'public-service.penalties.get-all',
    PublicServiceGetPenaltiesFromInspectorByDrl = 'public-service.penalties.get-inspectors-by-drl',
    PublicServiceGetPenaltiesByVehicleLicense = 'public-service.penalties.get-penalties-by-veh-cert',
    PublicServiceGetPenaltyDetailsBySn = 'public-service.penalties.get-details-by-sn',
    PublicServiceUpdatePenaltyPaymentStatus = 'public-service.penalties.update-payment-status',
    PublicServiceInternallyDisplacedPersonConvertApplication = 'public-service.internally-displaced-person.convert-application',
    PublicServiceInternallyDisplacedPersonConvertApplications = 'public-service.internally-displaced-person.convert-applications',
    PublicServiceInternallyDisplacedPersonDeconvertApplication = 'public-service.internally-displaced-person.deconvert-application',
    PublicServiceInternallyDisplacedPersonCheckApplication = 'public-service.internally-displaced-person.check-application',
    PublicServiceInternallyDisplacedPersonDeconvertCheckApplication = 'public-service.internally-displaced-person.deconvert-check-application',
    PublicServiceInternallyDisplacedPersonCancel = 'public-service.internally-displaced-person.cancel',
    PublicServiceInternallyDisplacedPersonChangeAddress = 'public-service.internally-displaced-person.change-address',
    PublicServiceInternallyDisplacedApplicationResult = 'public-service.internally-displaced-person.application.result',
    PublicServiceInternallyDisplacedPersonCancelProcessing = 'public-service.internally-displaced-person.cancel.processing',
    PublicServiceInternallyDisplacedPersonCancelResult = 'public-service.internally-displaced-person.cancel.result',
    PublicServiceUnemploymentStatusRegisterApplication = 'public-service.unemployment-status.register-application',
    PublicServiceUnemploymentStatusApplicationStatus = 'public-service.unemployment-status.application-status',
    PublicServiceUnemploymentBenefitsRegisterApplication = 'public-service.unemployment-benefits.register-application',
    PublicServiceUnemploymentBenefitsApplicationStatus = 'public-service.unemployment-benefits.application-status',
    PublicServiceUnemploymentStatusCancelingRegisterApplication = 'public-service.unemployment-status-canceling.register-application',
    PublicServiceUnemploymentStatusCancelingApplicationStatus = 'public-service.unemployment-status-canceling.application-status',
    PublicServiceENotGetSignatories = 'public-service.enot.get-signatories',
    PublicServiceENotGetSignature = 'public-service.enot.get-signature',
    PublicServiceENotGetDocument = 'public-service.enot.get-document',
    PublicServiceHomecomingIdentityCardCreation = 'public-service.homecoming-identity-card.creation',
    PublicServiceHomecomingIdentityCard = 'public-service.homecoming-identity-card',
    PublicServiceBondsAvailable = 'public-service.bonds.available',
    PublicServiceBondsDictionary = 'public-service.bonds.dictionary',
    PublicServiceBondsProperty = 'public-service.bonds.property',
    PublicServiceBondsGetDocuments = 'public-service.bonds.get-documents',
    PublicServiceBondsOrder = 'public-service.bonds.order',
    PublicServiceBondsStatements = 'public-service.bonds.statements',
    PublicServiceBondsOrderCancel = 'public-service.bonds.order.cancel',
    PublicServiceResidenceCertOrder = 'public-service.residence-cert.order',
    PublicServiceResidenceCert = 'public-service.residence-cert',
    PublicServiceResidenceCertData = 'public-service.residence-cert.data',
    PublicServiceCourtCases = 'public-service.court.cases',
    PublicServiceCourtCaseDetails = 'public-service.court.case.details',
    PublicServiceCourtDecisions = 'public-service.court.decisions',
    PublicServiceCourtDecisionDetails = 'public-service.court.decision.details',
    PublicServiceCourtTrials = 'public-service.court.trials',
    PublicServiceCourtTrialDetails = 'public-service.court.trial.details',
    PublicServiceCourtPenalties = 'public-service.court.penalties',
    PublicServiceCourtPenaltyDetails = 'public-service.court.penalty.details',
    PublicServiceCourtPenaltyAddPayment = 'public-service.court.penalty.add-payment',
    PublicServiceCriminalRecordCertOrder = 'public-service.criminal-record-cert.order',
    PublicServiceCriminalRecordCertDownload = 'public-service.criminal-record-cert.download',
    PublicServiceCriminalRecordCertOrderResult = 'public-service.criminal-record-cert.order.result',
    PublicServiceDebts = 'public-service.debts',
    PublicServiceDebtsNotification = 'public-service.debts.notification',
    PublicServiceDebtsAddOnlinePayment = 'public-service.debts.add-online-payment',
    PublicServiceMortgageApplicationSend = 'public-service.mortgage.application.send',
    PublicServiceMortgageApplicationStatus = 'public-service.mortgage.application.status',
    PublicServiceReportMoneyAidPca = 'public-service.report.money-aid.pca',
    PublicServiceReportMoneyAidPpr = 'public-service.report.money-aid.ppr',
    PublicServiceReportMoneyAidEnrollmentsUpdate = 'public-service.report.money-aid.enrollments.update',
    PublicServiceReportMortgageIssued = 'public-service.report.mortgage.issued',
    PublicServiceELightCheckAvailability = 'public-service.e-light.check-availability',
    PublicServiceELightGetReportByDate = 'public-service.e-light.get-report-by-date',
    PublicServiceELightUploadOrdersList = 'public-service.e-light.upload-orders-list',
    PublicServiceUkrpostGetPostofficesByPostcodeCityid = 'public-service.ukrpost.get-postoffices-by-postcode-cityid',
    PublicServiceProperUserAssignApplicationSend = 'public-service.proper-user-assign.application.send',
    PublicServiceProperUserCancelingApplicationSend = 'public-service.proper-user-canceling.application.send',
    PublicServiceHscGetDictionary = 'public-service.hsc.get-dictionary',
    PublicServiceDamagedPropertyRecoveryExtSearchInfoMessageByRnokpp = 'public-service.damaged-property-recovery.ext-search-info-message-by-rnokpp',
    PublicServiceDamagedPropertyRecoveryExtUpdateInfoMessageAfterDrrp = 'public-service.damaged-property-recovery.ext-update-info-message-after-drrp',
    PublicServiceDamagedPropertyRecoveryExtUpdateInfoMessageOwnerChanged = 'public-service.damaged-property-recovery.ext-update-info-message-owner-changed',
    PublicServiceDamagedPropertyRecoveryExtAutomaticDiiaApplication = 'public-service.damaged-property-recovery.ext-automatic-diia-application',
    PublicServiceDamagedPropertyRecoveryExtApplicationByDrrpIdRnokpp = 'public-service.damaged-property-recovery.ext-application-by-drrpid-rnokpp',
    PublicServiceDamagedPropertyRecoveryExtApplicationFullInfo = 'public-service.damaged-property-recovery.ext-application-full-info',
    PublicServiceDamagedPropertyRecoveryExtApplicationStatusInfo = 'public-service.damaged-property-recovery.ext-application-status-info',
    PublicServiceDamagedPropertyRecoveryExtApplicationStatusInfoUpdate = 'public-service.damaged-property-recovery.ext-application-status-info.update',
    PublicServiceDamagedPropertyExtSendInformationMessage = 'public-service.damaged-property.ext-send-information-message',
    PublicServiceDamagedPropertyRecoveryExtTrembitaApplicationDestroyedSaving = 'public-service.damaged-property-recovery.ext-trembita-application-destroyed-saving',
    PublicServiceDamagedPropertyRecoveryExtTrembitaApplicDuplicatesByOwnerCheck = 'public-service.damaged-property-recovery.ext-trembita-applic-duplicates-by-owner-check',
    PublicServiceDamagedPropertyRecoveryExtTrembitaCriminalRecordFileSaving = 'public-service.damaged-property-recovery.ext-trembita-criminal-record-file-saving',
    PublicServiceDamagedPropertyRecoveryExtTrembitaApplicationDestroyedFullInfoView = 'public-service.damaged-property-recovery.ext-trembita-application-destroyed-full-info-view',
    PublicServiceDamagedPropertyRecoveryExtTrembitaCoOwnerInformationMessageRead = 'public-service.damaged-property-recovery.ext-trembita-co-owner-information-message-read',
    PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificatesRead = 'public-service.damaged-property-recovery.ext-trembita-housing-certificates-read',
    PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificateFullInfoRead = 'public-service.damaged-property-recovery.ext-trembita-housing-certificate-full-info-read',
    PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificateExcerpt = 'public-service.damaged-property-recovery.ext-trembita-housing-certificate-excerpt',
    PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificateExcerptResult = 'public-service.damaged-property-recovery.ext-trembita-housing-certificate-excerpt.result',
    PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificateStatusRead = 'public-service.damaged-property-recovery.ext-trembita-housing-certificate-status-read.',
    PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificateStatusInfoUpdate = 'public-service.damaged-property-recovery.ext-trembita-housing-certificate-status-info.update',
    PublicServiceDamagedPropertyRecoveryExtTrembitaRepairCompletionMessageSaving = 'public-service.damaged-property-recovery.ext-trembita-repair-completion-message-saving',
    PublicServiceDamagedPropertyRecoveryExtTrembitaFundingRequestSaving = 'public-service.damaged-property-recovery.ext-trembita-funding-request-saving',
    PublicServiceDamagedPropertyRecoveryExtTrembitaMonetaryCompensationRead = 'public-service.damaged-property-recovery.ext-trembita-monetary-compensation-read',
    PublicServiceDamagedPropertyRecoveryExtTrembitaMonetaryCompensationFullInfoRead = 'public-service.damaged-property-recovery.ext-trembita-monetary-compensation-full-info-read',
    PublicServiceDamagedPropertyRecoveryExtTrembitaMonetaryCompensationStatusInfoUpdate = 'public-service.damaged-property-recovery.ext-trembita-monetary-compensation-status-info.update',
    PublicServiceDamagedPropertyRecoveryExtTrembitaConstructingStartMessageSaving = 'public-service.damaged-property-recovery.ext-trembita-constructing-start-message-saving',
    PublicServiceDamagedPropertyRecoveryExtTrembitaConstructingCompletionMessageSaving = 'public-service.damaged-property-recovery.ext-trembita-constructing-completion-message-saving',
    PublicServiceCompensationDepositsApplicationSend = 'public-service.compensation-deposits.application.send',
    PublicServiceCarReRegistrationExpertConclusion = 'public-service.car-re-registration.expert-conclusion',
    PublicServiceCarReRegistrationClntAdd = 'public-service.car-re-registration.clntadd',
    PublicServiceCarReRegistrationLicensePlate = 'public-service.car-re-registration.license-plate',
    PublicServiceCarReRegistrationLicensePlateList = 'public-service.car-re-registration.license-plates-list',
    PublicServiceCarReRegistrationLicensePlateReservation = 'public-service.car-re-registration.license-plate-reservation',
    PublicServiceCarReRegistrationCancelPlateReservation = 'public-service.car-re-registration.cancel-plate-reservation',
    PublicServiceCarReRegistrationApplicationSend = 'public-service.car-re-registration.application.send',
    PublicServiceCarReRegistrationCheckingResult = 'public-service.car-re-registration.application.checking-result',
    PublicServiceCarReRegistrationReceiptSend = 'public-service.car-re-registration.receipt.send',
    PublicServiceCarReRegistrationCancel = 'public-service.car-re-registration.cancel',
    PublicServiceDriverLicenseExchangeResult = 'public-service.driver-license.exchange.result',
    PublicServiceActNoteGetArByRnokpp = 'public-service.act-note.get-ar-by-rnokpp',
    PublicServiceInvincibilityPoints = 'public-service.invincibility-points',
    PublicServiceInvincibilityShelters = 'public-service.invincibility.shelters',
    PublicServiceInvincibilityPointsRating = 'public-service.invincibility-points.rating',
    PublicServiceInvincibilityPointsReviews = 'public-service.get-invincibility-points.reviews',
    PublicServiceInvincibilityPointsAllReviews = 'public-service.invincibility-points.all-reviews',
    PublicServiceInfotechDeliveryOrderCreate = 'public-service.infotech.delivery.order.create',
    PublicServiceInfotechDeliveryOrderOffertSend = 'public-service.infotech.delivery.order.offert.send',
    PublicServiceDroneArmyRegisterApplication = 'public-service.drone-army.register-application',
    PublicServiceNewsAction = 'public-service.news.action',
    PublicServiceGetBanksByService = 'public-service.get-banks-by-service',
    PublicServiceGetUserCardsByService = 'public-service.get-user-cards-by-service',
    PublicServiceNazkSendConfirmationProposals = 'public-service.nazk.send-confirmation-proposals',
    PublicServiceNazkGetConfirmationResult = 'public-service.nazk.get-confirmation-result',

    UserGetInfoForFilters = 'user-service.get-info.filters',

    AppealRequest = 'appeal.request',

    VoteJoinPetitions = 'vote.join.petitions',
    VoteJoinCommunity = 'vote.join-community',
    VotePetitionAnswer = 'vote.petition.answer',
    VotePetitionCategories = 'vote.petition.categories',
    VotePetitionCreate = 'vote.petition.create',
    VotePetitionFollowers = 'vote.petition.followers',
    VotePetitionInformation = 'vote.petition.information',
    VotePetitionSign = 'vote.petition.sign',
    VotePetitionsSearch = 'vote.petitions.search',

    VotePortalJoinCommunity = 'vote.portal.join-community',
    VotePortalPetitionAnswer = 'vote.portal.petition.answer',
    VotePortalPetitionCategories = 'vote.portal.petition.categories',
    VotePortalPetitionCreate = 'vote.portal.petition.create',
    VotePortalPetitionFollowers = 'vote.portal.petition.followers',
    VotePortalPetitionInformation = 'vote.portal.petition.information',
    VotePortalPetitionSign = 'vote.portal.petition.sign',
    VotePortalPetitionsSearch = 'vote.portal.petitions.search',

    VoteBackstagePetitionAdminCommunitiesList = 'vote.backstage.petition.admin.communities.list',
    VoteBackstagePetitionAdminCommunity = 'vote.backstage.petition.admin.community',
    VoteBackstagePetitionAdminCommunityUpdate = 'vote.backstage.petition.admin.community.update',
    VoteBackstagePetitionAdminCommunityCreate = 'vote.backstage.petition.admin.community.create',
    VoteBackstagePetitionAdminStatistic = 'vote.backstage.petition.admin.statistic',
    VoteBackstagePetitionAdminUsers = 'vote.backstage.petition.admin.users',
    VoteBackstagePetitionAdminUserPetitions = 'vote.backstage.petition.admin.user.petitions',

    VoteBackstagePetitionsSearch = 'vote.backstage.petitions.search',
    VoteBackstagePetitionInformation = 'vote.backstage.petition.information',
    VoteBackstagePetitionUpdate = 'vote.backstage.petition.update',
    VoteBackstagePetitionUserInfo = 'vote.backstage.petition.userInfo',
    VoteBackstagePetitionCommunityStatistic = 'vote.backstage.petition.communityStatistic',
    VoteBackstageCommunityInfo = 'vote.backstage.community.info',

    VotePollList = 'vote.poll.list',
    VotePollDetails = 'vote.poll.details',
    VotePollSubmit = 'vote.poll.submit',
    VoteBackstagePollCreate = 'vote.backstage.poll.create',
    VoteBackstagePollUpdate = 'vote.backstage.poll.update',
    VoteBackstagePollClose = 'vote.backstage.poll.close',
    VoteBackstagePollPublish = 'vote.backstage.poll.publish',
    VoteBackstagePollList = 'vote.backstage.poll.list',
    VoteBackstagePollDetails = 'vote.backstage.poll.details',
    VoteBackstagePollHistory = 'vote.backstage.poll.history',
    VoteBackstagePollLaunch = 'vote.backstage.poll.launch',
    VoteBackstagePollResults = 'vote.backstage.poll.results',
    VoteBackstagePollUserAdd = 'vote.backstage.poll.user.add',

    MedicalDataTransfer = 'medical.data.transfer',
    MedicalDataTransferResult = 'medical.data.transfer.result',

    PensionFundPfuAuth = 'pension-fund.pfu-auth',
    PensionFundGeneralPersonData = 'pension-fund.general-person-data',
    PensionFundPersonInsuredData = 'pension-fund.person-insured-data',
    PensionFundPensionCardData = 'pension-fund.pension-card-data',
    PensionFundInitExternalSession = 'pension-fund.init-external-session',

    AcquirerDocumentRequest = 'acquirer.document-request',
    AcquirerDocumentResponse = 'acquirer.document-response',

    DeltaShareObjects = 'delta.share-objects',

    CheckUnzr = 'checkunzr',

    GetAtuList = 'get-atu-list',

    GetArOfDeath = 'mju.get-dead-ar-by-fullname-and-birthdate',
    GetMarriageArByRnokpp = 'mju.get-marriage-ar-by-rnokpp',
    GetDivorceArByRnokpp = 'mju.get-divorce-ar-by-rnokpp',

    TemporaryOccupiedTerritories = 'moi.temporarily-occupied-territories',

    SuperGenGeneratePdfDocument = 'supergen.generate.pdf.document',

    OfficeIdentifier = 'office.identifier',
    OfficeIdentifierRemoved = 'office.identifier.removed',
    OfficeIdentifierTokenFail = 'office.identifier.token.fail',
    OfficeProfileMy = 'office.profile.my',
    OfficeProfileDetails = 'office.profile.details',

    OfficeSearchFields = 'office.search.fields',
    OfficeSearchFacets = 'office.search.facets',
    OfficeSearchPeople = 'office.search.people',
    OfficeSearchAutocomplete = 'office.search.autocomplete',

    OfficeBadgeAvailable = 'office.badge.available',
    OfficeBadgeDetails = 'office.badge.details',

    OfficeBadgeProfileList = 'office.badge.profile.list',
    OfficeBadgeProfileGive = 'office.badge.profile.give',

    OfficePhoto = 'office.photo',

    OfficePollCreateAndPublish = 'vote.diia-office.poll.createAndPublish',
    OfficePollGet = 'vote.diia-office.poll.get',
    OfficePollOnboarding = 'vote.diia-office.poll.onboarding',
    OfficePollDelete = 'vote.diia-office.poll.delete',
    OfficePollCount = 'vote.diia-office.poll.count',

    NotificationCampaignStatusReady = 'notification.campaign.status.ready',
    NotificationCampaignCreate = 'notification.campaign.create',
    NotificationCampaignJoinUsers = 'notification.campaign.join.users',
    NotificationCampaignSendMessage = 'notification.campaign.send.message',
}

export type EventName = InternalEvent | ScheduledTaskEvent | ExternalEvent
