export enum InternalTopic {
    TopicAcquirersOfferRequestLifeCycle = 'TopicAcquirersOfferRequestLifeCycle',
    TopicAuthUserSession = 'TopicAuthUserSession',
    TopicDocumentsRegistry = 'TopicDocumentsRegistry',
    TopicGatewayUserActivity = 'TopicGatewayUserActivity',
    TopicNotificationLifeCycle = 'TopicNotificationLifeCycle',
    TopicPaymentDataLifeCycle = 'TopicPaymentDataLifeCycle',
    TopicPublicServiceDebtsLifeCycle = 'TopicPublicServiceDebtsLifeCycle',
    TopicPublicServicePenaltiesLifeCycle = 'TopicPublicServicePenaltiesLifeCycle',
    TopicPublicServiceCriminalCertLifeCycle = 'TopicPublicServiceCriminalCertLifeCycle',
    TopicPublicServiceSigningLifeCycle = 'TopicPublicServiceSigningLifeCycle',
    TopicDocumentLifeCycle = 'TopicDocumentLifeCycle',
    TopicUserSendMassNotifications = 'TopicUserSendMassNotifications',
    TopicUserProfileLifecycle = 'TopicUserProfileLifecycle',
    TopicUserPenaltiesIdentification = 'TopicUserPenaltiesIdentification',
    TopicPartnerLifeCycle = 'TopicPartnerLifeCycle',
    TopicAnalytics = 'TopicAnalytics',
    TopicRating = 'TopicRating',
    TopicDocumentDeliveryLifeCycle = 'TopicDocumentDeliveryLifeCycle',
    TopicCriminalCertLifeCycle = 'TopicCriminalCertLifeCycle',

    TopicScheduledTasks = 'TopicScheduledTasks',
}

export enum ExternalTopic {
    Aid = 'Aid',
    Attestation = 'Attestation',
    BankAccount = 'BankAccount',
    Ubki = 'Ubki',
    DgcValidator = 'DgcValidator',
    DiiaId = 'DiiaId',
    Document = 'Document',
    EResident = 'EResident',
    FaceReco = 'FaceReco',
    Notification = 'Notification',
    NotificationDistribution = 'NotificationDistribution',
    Repo = 'Repo',
    TaxCabinet = 'TaxCabinet',
    Vote = 'Vote',
    Poll = 'Poll',
    OfficePoll = 'OfficePoll',
    Medical = 'Medical',
    CriminalRecord = 'CriminalRecord',
    Pfu = 'Pfu',
    AcquirerSharing = 'AcquirerSharing',
    Delta = 'Delta',
    DirectRPC = 'DirectRPC',
    User = 'User',
    Auth = 'Auth',
    SuperGen = 'SuperGen',
    Office = 'Office',
    NotificationCampaign = 'NotificationCampaign',
}

export type Topic = InternalTopic | ExternalTopic
