import {
    ExternalEvent,
    ExternalTopic,
    InternalEvent,
    InternalQueueName,
    InternalTopic,
    QueueConfig,
    QueueConfigType,
    ScheduledTaskEvent,
    ScheduledTaskQueueName,
    ServiceConfig,
    TopicConfig,
} from '../interfaces/queueConfig'

// list of queues and topics for each service
export const servicesConfig: ServiceConfig = {
    [QueueConfigType.Internal]: {
        Notification: {
            subscribe: [ScheduledTaskQueueName.ScheduledTasksQueueNotification, InternalQueueName.QueueNotification],
            publish: [InternalTopic.TopicNotificationLifeCycle],
        },
        Scheduler: {
            publish: [InternalTopic.TopicScheduledTasks],
        },
        Auth: {
            subscribe: [ScheduledTaskQueueName.ScheduledTasksQueueAuth, InternalQueueName.QueueAuth],
            publish: [InternalTopic.TopicAuthUserSession],
        },
        DamagedProperty: {
            subscribe: [ScheduledTaskQueueName.ScheduledTasksQueueDamagedProperty, InternalQueueName.QueueDamagedProperty],
            publish: [InternalTopic.TopicAnalytics],
        },
        DepositGuaranteePayments: {
            subscribe: [ScheduledTaskQueueName.ScheduledTasksQueueDepositGuaranteePayments],
            publish: [InternalTopic.TopicAnalytics],
        },
        Documents: {
            subscribe: [ScheduledTaskQueueName.ScheduledTasksQueueDocuments, InternalQueueName.QueueDocuments],
            publish: [InternalTopic.TopicDocumentsRegistry, InternalTopic.TopicDocumentLifeCycle],
        },
        Gateway: {
            subscribe: [ScheduledTaskQueueName.ScheduledTasksQueueGateway],
            publish: [InternalTopic.TopicGatewayUserActivity],
        },
        Payment: {
            subscribe: [InternalQueueName.QueuePayment, ScheduledTaskQueueName.ScheduledTasksQueuePayment],
            publish: [InternalTopic.TopicPaymentDataLifeCycle],
        },
        PublicService: {
            subscribe: [ScheduledTaskQueueName.ScheduledTasksQueuePublicService, InternalQueueName.QueuePublicService],
            publish: [
                InternalTopic.TopicPaymentDataLifeCycle,
                InternalTopic.TopicPublicServicePenaltiesLifeCycle,
                InternalTopic.TopicPublicServiceCriminalCertLifeCycle,
                InternalTopic.TopicPublicServiceDebtsLifeCycle,
                InternalTopic.TopicPublicServiceSigningLifeCycle,
                InternalTopic.TopicAnalytics,
            ],
        },
        CriminalCert: {
            subscribe: [ScheduledTaskQueueName.ScheduledTasksQueueCriminalCert, InternalQueueName.QueueCriminalCert],
            publish: [InternalTopic.TopicCriminalCertLifeCycle, InternalTopic.TopicAnalytics],
        },
        ReportService: {
            subscribe: [ScheduledTaskQueueName.ScheduledTasksQueueReportService],
        },
        ResidenceRegistration: {
            subscribe: [ScheduledTaskQueueName.ScheduledTasksQueueResidenceRegistration],
            publish: [InternalTopic.TopicPaymentDataLifeCycle, InternalTopic.TopicAnalytics],
        },
        VehicleReRegistration: {
            subscribe: [ScheduledTaskQueueName.ScheduledTasksQueueVehicleReRegistration],
            publish: [InternalTopic.TopicPaymentDataLifeCycle, InternalTopic.TopicAnalytics],
        },
        Marriage: {
            subscribe: [],
            publish: [],
        },
        Invincibility: {
            subscribe: [ScheduledTaskQueueName.ScheduledTasksQueueInvincibility, InternalQueueName.QueueInvincibility],
        },
        User: {
            subscribe: [ScheduledTaskQueueName.ScheduledTasksQueueUser, InternalQueueName.QueueUser],
            publish: [
                InternalTopic.TopicUserPenaltiesIdentification,
                InternalTopic.TopicUserSendMassNotifications,
                InternalTopic.TopicUserProfileLifecycle,
                InternalTopic.TopicAnalytics,
            ],
        },
        DocumentAcquirers: {
            subscribe: [ScheduledTaskQueueName.ScheduledTasksQueueDocumentAcquirers],
            publish: [InternalTopic.TopicAcquirersOfferRequestLifeCycle],
        },
        SseAdapter: {
            subscribe: [InternalQueueName.QueueSseAdapter],
        },
        Vote: {
            subscribe: [InternalQueueName.QueueVote],
        },
        Partner: {
            subscribe: [InternalQueueName.QueuePartner, ScheduledTaskQueueName.ScheduledTasksQueuePartner],
        },
        Address: {
            subscribe: [ScheduledTaskQueueName.ScheduledTasksQueueAddress],
        },
        Analytics: {
            subscribe: [InternalQueueName.QueueAnalytics],
            publish: [InternalTopic.TopicRating],
        },
        DocumentDelivery: {
            subscribe: [InternalQueueName.QueueDocumentDelivery, ScheduledTaskQueueName.ScheduledTasksQueueDocumentDelivery],
            publish: [InternalTopic.TopicDocumentDeliveryLifeCycle],
        },
    },
    [QueueConfigType.External]: {
        Auth: {
            subscribe: [ExternalEvent.AuthSaveNfcScanResult],
            publish: [
                ExternalEvent.AttestationGoogleDevice,
                ExternalEvent.IntegrityGoogleDevice,
                ExternalEvent.AttestationHuaweiDevice,
                ExternalEvent.FaceRecoAuthPhotoVerification,
                ExternalEvent.RepoAuthEisAgree,
                ExternalEvent.EResidentAuthConfirmation,
                ExternalEvent.AuthGetInnByUnzr,
                ExternalEvent.FaceRecoAuthNfcUserPersist,
            ],
        },
        Gateway: {
            subscribe: [
                ExternalEvent.NotificationTemplateCreate,
                ExternalEvent.NotificationDistributionCreate,
                ExternalEvent.NotificationDistributionStatus,
                ExternalEvent.NotificationDistributionStatusRecipients,
                ExternalEvent.NotificationDistributionCancel,
            ],
            publish: [],
        },
        Notification: {
            subscribe: [
                ExternalEvent.NotificationSend,
                ExternalEvent.NotificationTopicSubscribe,
                ExternalEvent.NotificationTopicUnsubscribe,
                ExternalEvent.NotificationCampaignCreate,
                ExternalEvent.NotificationCampaignJoinUsers,
                ExternalEvent.NotificationCampaignSendMessage,
            ],
            publish: [
                ExternalEvent.NotificationSendEmail,
                ExternalEvent.NotificationSendSms,
                ExternalEvent.NotificationSendPush,
                ExternalEvent.NotificationPushTopicSubscribe,
                ExternalEvent.NotificationPushTopicUnsubscribe,
                ExternalEvent.NotificationTopicSubscribeTarget,
                ExternalEvent.NotificationCampaignStatusReady,
            ],
        },
        User: {
            subscribe: [
                ExternalEvent.NotificationSendTarget,
                ExternalEvent.NotificationTopicSubscribeTarget,
                ExternalEvent.UserGetInfoForFilters,
                ExternalEvent.OfficeIdentifierRemoved,
                ExternalEvent.OfficeIdentifierTokenFail,
            ],
            publish: [
                ExternalEvent.FaceRecoUserPhotoExtractFeaturePoints,
                ExternalEvent.DiiaIdCertificateInfo,
                ExternalEvent.FaceRecoUserPhotoMatch,
                ExternalEvent.DiiaIdCertificateCreate,
                ExternalEvent.DiiaIdCertificateRevoke,
                ExternalEvent.DiiaIdCertificateRevokeAll,
                ExternalEvent.DiiaIdHashFiles,
                ExternalEvent.DiiaIdSignHashesInit,
                ExternalEvent.DiiaIdHashFilesIntegrity,
                ExternalEvent.DiiaIdSignDpsPackageInit,
                ExternalEvent.DiiaIdSignDpsPackagePrepare,
                ExternalEvent.UbkiCreditInfo,
                ExternalEvent.NotificationTopicSubscribe,
                ExternalEvent.EResidentDiiaIdCreation,
                ExternalEvent.OfficeIdentifier,
            ],
        },
        DamagedProperty: {
            subscribe: [
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtApplicationStatusInfoUpdate,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificateStatusInfoUpdate,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificateExcerptResult,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaMonetaryCompensationStatusInfoUpdate,
            ],
            publish: [
                ExternalEvent.PublicServiceDrrpExtSearch,
                ExternalEvent.PublicServiceDrrpExtGroup,
                ExternalEvent.PublicServiceDrrpGetActualAtu,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtSearchInfoMessageByRnokpp,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtUpdateInfoMessageAfterDrrp,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtUpdateInfoMessageOwnerChanged,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtAutomaticDiiaApplication,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtApplicationByDrrpIdRnokpp,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtApplicationFullInfo,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtApplicationStatusInfo,
                ExternalEvent.PublicServiceDamagedPropertyExtSendInformationMessage,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaApplicationDestroyedSaving,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaApplicDuplicatesByOwnerCheck,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaCriminalRecordFileSaving,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaApplicationDestroyedFullInfoView,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaCoOwnerInformationMessageRead,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificatesRead,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificateFullInfoRead,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificateExcerpt,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificateStatusRead,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaRepairCompletionMessageSaving,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaFundingRequestSaving,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaMonetaryCompensationRead,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaMonetaryCompensationFullInfoRead,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaConstructingStartMessageSaving,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaConstructingCompletionMessageSaving,
            ],
        },
        DocumentDelivery: {
            subscribe: [],
            publish: [ExternalEvent.PublicServiceInfotechDeliveryOrderCreate, ExternalEvent.PublicServiceInfotechDeliveryOrderOffertSend],
        },
        DepositGuaranteePayments: {
            subscribe: [],
            publish: [ExternalEvent.PublicServiceCompensationDepositsApplicationSend],
        },
        Documents: {
            subscribe: [],
            publish: [
                ExternalEvent.DgcValidate,
                ExternalEvent.RepoDocumentInternalPassport,
                ExternalEvent.RepoDocumentDriverLicense,
                ExternalEvent.RepoDocumentVehicleLicenses,
                ExternalEvent.RepoDocumentVehicleLicenseOwner,
                ExternalEvent.RepoDocumentVehicleLicenseProper,
                ExternalEvent.RepoDocumentVehicleInsurance,
                ExternalEvent.RepoDocumentStudentIdCard,
                ExternalEvent.RepoDocumentInternalPassport,
                ExternalEvent.RepoDocumentForeignPassport,
                ExternalEvent.RepoDocumentPassports,
                ExternalEvent.RepoDocumentPassportsByInn,
                ExternalEvent.RepoDocumentTaxpayerCard,
                ExternalEvent.RepoDocumentRefInternallyDisplacedPerson,
                ExternalEvent.RepoDocumentBirthCertificate,
                ExternalEvent.PensionFundPfuAuth,
                ExternalEvent.EResidentDocuments,
                ExternalEvent.DocumentEducation,
                ExternalEvent.RepoDocumentRnokpp,
                ExternalEvent.RepoDocumentPensionCard,
                ExternalEvent.RepoDocumentCovidCertSign,
                ExternalEvent.RepoDocumentCovidCertVerify,
                ExternalEvent.PensionFundInitExternalSession,
                ExternalEvent.RepoDocumentEPermit,
                ExternalEvent.OfficeProfileMy,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificatesRead,
                ExternalEvent.GetArOfDeath,
                ExternalEvent.PublicServiceActNoteGetArByRnokpp,
            ],
        },
        SseAdapter: {
            subscribe: [],
            publish: [],
        },
        DocumentAcquirers: {
            subscribe: [ExternalEvent.AcquirerDocumentRequest],
            publish: [ExternalEvent.AcquirerDocumentResponse],
        },
        Partner: {
            subscribe: [ExternalEvent.PublicServiceGetBanksByService, ExternalEvent.PublicServiceGetUserCardsByService],
            publish: [],
        },
        PublicService: {
            subscribe: [
                ExternalEvent.DocumentCovidCertificateProcessing,
                ExternalEvent.DocumentCovidCertificate,
                ExternalEvent.DocumentResidenceCertProcessing,
                ExternalEvent.DocumentResidenceCert,
                ExternalEvent.PublicServiceResidenceCert,
                ExternalEvent.PublicServiceInternallyDisplacedApplicationResult,
                ExternalEvent.PublicServiceInternallyDisplacedPersonCancelProcessing,
                ExternalEvent.PublicServiceReportMoneyAidPca,
                ExternalEvent.PublicServiceReportMoneyAidPpr,
                ExternalEvent.PublicServiceReportMoneyAidEnrollmentsUpdate,
                ExternalEvent.PublicServiceReportMortgageIssued,
                ExternalEvent.PublicServiceNazkGetConfirmationResult,
                ExternalEvent.PublicServiceNazkSendConfirmationProposals,
            ],
            publish: [
                ExternalEvent.PrivateEntrepreneurPayerCredentials,
                ExternalEvent.PrivateEntrepreneurBankAccounts,
                ExternalEvent.PrivateEntrepreneurTaxAccounts,
                ExternalEvent.PrivateEntrepreneurBankAccountIncomePeriod,
                ExternalEvent.PrivateEntrepreneurBankAccountReportPeriod,
                ExternalEvent.PrivateEntrepreneurPayerDeclaration,
                ExternalEvent.PayerIncomeQuery,
                ExternalEvent.PayerIncomeAnswer,
                ExternalEvent.PublicServiceDrrpExtSearch,
                ExternalEvent.PublicServiceDrrpExtGroup,
                ExternalEvent.PublicServiceDrrpGetActualAtu,
                ExternalEvent.PublicServiceDriverLicenseExchangeApplication,
                ExternalEvent.PublicServiceDriverLicenseExchangePayment,
                ExternalEvent.PublicServiceInfotechDeliveryOrderCreate,
                ExternalEvent.PublicServiceInfotechDeliveryOrderOffertSend,
                ExternalEvent.PublicServiceGetPenaltiesByPeriod,
                ExternalEvent.PublicServiceGetPenaltiesFromInspectorByDrl,
                ExternalEvent.PublicServiceGetPenaltiesByVehicleLicense,
                ExternalEvent.PublicServiceGetPenaltyDetailsBySn,
                ExternalEvent.PublicServiceUpdatePenaltyPaymentStatus,
                ExternalEvent.PublicServiceUnemploymentStatusRegisterApplication,
                ExternalEvent.PublicServiceUnemploymentStatusApplicationStatus,
                ExternalEvent.PublicServiceUnemploymentBenefitsRegisterApplication,
                ExternalEvent.PublicServiceUnemploymentBenefitsApplicationStatus,
                ExternalEvent.PublicServiceUnemploymentStatusCancelingRegisterApplication,
                ExternalEvent.PublicServiceUnemploymentStatusCancelingApplicationStatus,
                ExternalEvent.MedicalDataTransfer,
                ExternalEvent.MedicalDataTransferResult,
                ExternalEvent.PensionFundPfuAuth,
                ExternalEvent.AidVaccinationStatus,
                ExternalEvent.DeltaShareObjects,
                ExternalEvent.PublicServiceInternallyDisplacedPersonConvertApplication,
                ExternalEvent.PublicServiceInternallyDisplacedPersonConvertApplications,
                ExternalEvent.PublicServiceInternallyDisplacedPersonDeconvertApplication,
                ExternalEvent.PublicServiceInternallyDisplacedPersonCheckApplication,
                ExternalEvent.PublicServiceInternallyDisplacedPersonDeconvertCheckApplication,
                ExternalEvent.PublicServiceInternallyDisplacedPersonCancel,
                ExternalEvent.PublicServiceInternallyDisplacedPersonChangeAddress,
                ExternalEvent.PublicServiceInternallyDisplacedPersonCancelResult,
                ExternalEvent.AppealRequest,
                ExternalEvent.PublicServiceENotGetSignatories,
                ExternalEvent.PublicServiceENotGetSignature,
                ExternalEvent.PublicServiceENotGetDocument,
                ExternalEvent.PublicServiceHomecomingIdentityCardCreation,
                ExternalEvent.PublicServiceHomecomingIdentityCard,
                ExternalEvent.PublicServiceBondsAvailable,
                ExternalEvent.PublicServiceBondsDictionary,
                ExternalEvent.PublicServiceBondsProperty,
                ExternalEvent.PublicServiceBondsGetDocuments,
                ExternalEvent.PublicServiceBondsOrder,
                ExternalEvent.PublicServiceBondsStatements,
                ExternalEvent.PublicServiceBondsOrderCancel,
                ExternalEvent.PublicServiceResidenceCertOrder,
                ExternalEvent.PublicServiceCourtCases,
                ExternalEvent.PublicServiceCourtCaseDetails,
                ExternalEvent.PublicServiceCourtDecisions,
                ExternalEvent.PublicServiceCourtDecisionDetails,
                ExternalEvent.PublicServiceCourtTrials,
                ExternalEvent.PublicServiceCourtTrialDetails,
                ExternalEvent.PublicServiceCourtPenalties,
                ExternalEvent.PublicServiceCourtPenaltyDetails,
                ExternalEvent.PublicServiceCourtPenaltyAddPayment,
                ExternalEvent.PublicServiceMortgageApplicationSend,
                ExternalEvent.PublicServiceMortgageApplicationStatus,
                ExternalEvent.PensionFundGeneralPersonData,
                ExternalEvent.PensionFundPersonInsuredData,
                ExternalEvent.PensionFundPensionCardData,
                ExternalEvent.PublicServiceDebts,
                ExternalEvent.PublicServiceDebtsNotification,
                ExternalEvent.PublicServiceDebtsAddOnlinePayment,
                ExternalEvent.TemporaryOccupiedTerritories,
                ExternalEvent.PublicServiceELightCheckAvailability,
                ExternalEvent.PublicServiceELightGetReportByDate,
                ExternalEvent.PublicServiceELightUploadOrdersList,
                ExternalEvent.PublicServiceProperUserAssignApplicationSend,
                ExternalEvent.PublicServiceProperUserCancelingApplicationSend,
                ExternalEvent.PublicServiceHscGetDictionary,
            ],
        },
        CriminalCert: {
            subscribe: [],
            publish: [
                ExternalEvent.PublicServiceCriminalRecordCertOrder,
                ExternalEvent.PublicServiceCriminalRecordCertDownload,
                ExternalEvent.PublicServiceCriminalRecordCertOrderResult,
            ],
        },
        ResidenceRegistration: {
            subscribe: [],
            publish: [
                ExternalEvent.RepoDmsUnitedTerritorialCommunitySendApplicationForRegistrationOfResidence,
                ExternalEvent.RepoDmsUnitedTerritorialCommunityResultApplicationForRegistrationOfResidence,
                ExternalEvent.GetArOfDeath,
                ExternalEvent.PublicServiceDrrpExtSearch,
                ExternalEvent.PublicServiceDrrpExtGroup,
                ExternalEvent.PublicServiceDrrpGetActualAtu,
                ExternalEvent.PublicServiceResidenceCertData,
            ],
        },
        VehicleReRegistration: {
            subscribe: [],
            publish: [
                ExternalEvent.PublicServiceCarReRegistrationExpertConclusion,
                ExternalEvent.PublicServiceCarReRegistrationLicensePlate,
                ExternalEvent.PublicServiceCarReRegistrationLicensePlateList,
                ExternalEvent.PublicServiceCarReRegistrationLicensePlateReservation,
                ExternalEvent.PublicServiceCarReRegistrationCancelPlateReservation,
                ExternalEvent.PublicServiceCarReRegistrationApplicationSend,
                ExternalEvent.PublicServiceCarReRegistrationCheckingResult,
                ExternalEvent.PublicServiceCarReRegistrationReceiptSend,
                ExternalEvent.PublicServiceDriverLicenseExchangeResult,
                ExternalEvent.PublicServiceCarReRegistrationClntAdd,
                ExternalEvent.PublicServiceCarReRegistrationCancel,
            ],
        },
        Marriage: {
            subscribe: [],
            publish: [],
        },
        Feed: {
            subscribe: [ExternalEvent.PublicServiceNewsAction],
            publish: [],
        },
        Invincibility: {
            subscribe: [
                ExternalEvent.PublicServiceInvincibilityPointsRating,
                ExternalEvent.PublicServiceInvincibilityPointsReviews,
                ExternalEvent.PublicServiceInvincibilityPointsAllReviews,
            ],
            publish: [ExternalEvent.PublicServiceInvincibilityShelters, ExternalEvent.PublicServiceInvincibilityPoints],
        },
        Vote: {
            subscribe: [],
            publish: [
                ExternalEvent.VoteJoinPetitions,
                ExternalEvent.VoteJoinCommunity,
                ExternalEvent.VotePetitionAnswer,
                ExternalEvent.VotePetitionCategories,
                ExternalEvent.VotePetitionCreate,
                ExternalEvent.VotePetitionFollowers,
                ExternalEvent.VotePetitionInformation,
                ExternalEvent.VotePetitionSign,
                ExternalEvent.VotePetitionsSearch,

                ExternalEvent.VotePortalJoinCommunity,
                ExternalEvent.VotePortalPetitionAnswer,
                ExternalEvent.VotePortalPetitionCategories,
                ExternalEvent.VotePortalPetitionCreate,
                ExternalEvent.VotePortalPetitionFollowers,
                ExternalEvent.VotePortalPetitionInformation,
                ExternalEvent.VotePortalPetitionSign,
                ExternalEvent.VotePortalPetitionsSearch,

                ExternalEvent.VoteBackstagePetitionAdminCommunitiesList,
                ExternalEvent.VoteBackstagePetitionAdminCommunity,
                ExternalEvent.VoteBackstagePetitionAdminCommunityUpdate,
                ExternalEvent.VoteBackstagePetitionAdminCommunityCreate,
                ExternalEvent.VoteBackstagePetitionAdminStatistic,
                ExternalEvent.VoteBackstagePetitionAdminUsers,
                ExternalEvent.VoteBackstagePetitionAdminUserPetitions,

                ExternalEvent.VoteBackstagePetitionsSearch,
                ExternalEvent.VoteBackstagePetitionInformation,
                ExternalEvent.VoteBackstagePetitionUpdate,
                ExternalEvent.VoteBackstagePetitionUserInfo,
                ExternalEvent.VoteBackstagePetitionCommunityStatistic,
                ExternalEvent.VoteBackstageCommunityInfo,

                ExternalEvent.VotePollList,
                ExternalEvent.VotePollDetails,
                ExternalEvent.VotePollSubmit,
                ExternalEvent.VoteBackstagePollCreate,
                ExternalEvent.VoteBackstagePollUpdate,
                ExternalEvent.VoteBackstagePollClose,
                ExternalEvent.VoteBackstagePollPublish,
                ExternalEvent.VoteBackstagePollList,
                ExternalEvent.VoteBackstagePollDetails,
                ExternalEvent.VoteBackstagePollHistory,
                ExternalEvent.VoteBackstagePollLaunch,
                ExternalEvent.VoteBackstagePollResults,
                ExternalEvent.VoteBackstagePollUserAdd,
            ],
        },
        PrivateEntrepreneur: {
            subscribe: [],
            publish: [ExternalEvent.CheckUnzr],
        },
        Address: {
            subscribe: [],
            publish: [
                ExternalEvent.GetAtuList,
                ExternalEvent.PublicServiceUkrpostGetPostofficesByPostcodeCityid,
                ExternalEvent.PublicServiceDrrpExtSearch,
                ExternalEvent.PublicServiceDrrpExtGroup,
                ExternalEvent.PublicServiceDrrpGetActualAtu,
            ],
        },
        SuperGen: {
            subscribe: [ExternalEvent.SuperGenGeneratePdfDocument],
            publish: [],
        },
    },
}

// configuration for each queue: list of topics that can publish to the queue and queue config
export const queuesConfig: QueueConfig = {
    [QueueConfigType.Internal]: {
        [InternalQueueName.QueueNotification]: {
            topics: [
                InternalTopic.TopicUserPenaltiesIdentification,
                InternalTopic.TopicPublicServiceDebtsLifeCycle,
                InternalTopic.TopicUserSendMassNotifications,
                InternalTopic.TopicUserProfileLifecycle,
                InternalTopic.TopicAuthUserSession,
            ],
        },
        [InternalQueueName.QueuePayment]: {
            topics: [InternalTopic.TopicPaymentDataLifeCycle],
        },
        [InternalQueueName.QueuePublicService]: {
            topics: [
                InternalTopic.TopicPaymentDataLifeCycle,
                InternalTopic.TopicNotificationLifeCycle,
                InternalTopic.TopicDocumentLifeCycle,
                InternalTopic.TopicUserProfileLifecycle,
                InternalTopic.TopicDocumentDeliveryLifeCycle,
            ],
        },
        [InternalQueueName.QueueCriminalCert]: {
            topics: [],
        },
        [InternalQueueName.QueueDamagedProperty]: {
            topics: [InternalTopic.TopicPublicServiceCriminalCertLifeCycle, InternalTopic.TopicCriminalCertLifeCycle],
        },
        [InternalQueueName.QueueInvincibility]: {
            topics: [InternalTopic.TopicRating],
        },
        [InternalQueueName.QueueUser]: {
            topics: [
                InternalTopic.TopicDocumentsRegistry,
                InternalTopic.TopicPublicServicePenaltiesLifeCycle,
                InternalTopic.TopicPublicServiceSigningLifeCycle,
                InternalTopic.TopicAuthUserSession,
                InternalTopic.TopicAcquirersOfferRequestLifeCycle,
            ],
        },
        [InternalQueueName.QueueDocuments]: {
            topics: [InternalTopic.TopicAuthUserSession],
        },
        [InternalQueueName.QueueAuth]: {
            topics: [InternalTopic.TopicAcquirersOfferRequestLifeCycle, InternalTopic.TopicGatewayUserActivity],
        },
        [InternalQueueName.QueueVote]: {
            topics: [InternalTopic.TopicDocumentsRegistry],
        },
        [InternalQueueName.QueuePartner]: {
            topics: [InternalTopic.TopicPartnerLifeCycle],
        },
        [InternalQueueName.QueueAnalytics]: {
            topics: [InternalTopic.TopicAnalytics],
        },
        [InternalQueueName.QueueDocumentDelivery]: {
            topics: [],
        },

        [ScheduledTaskQueueName.ScheduledTasksQueueAuth]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
        [ScheduledTaskQueueName.ScheduledTasksQueueDamagedProperty]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
        [ScheduledTaskQueueName.ScheduledTasksQueueDepositGuaranteePayments]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
        [ScheduledTaskQueueName.ScheduledTasksQueueDocuments]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
        [ScheduledTaskQueueName.ScheduledTasksQueueGateway]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
        [ScheduledTaskQueueName.ScheduledTasksQueuePartner]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
        [ScheduledTaskQueueName.ScheduledTasksQueuePayment]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
        [ScheduledTaskQueueName.ScheduledTasksQueuePublicService]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
        [ScheduledTaskQueueName.ScheduledTasksQueueCriminalCert]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
        [ScheduledTaskQueueName.ScheduledTasksQueueReportService]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
        [ScheduledTaskQueueName.ScheduledTasksQueueResidenceRegistration]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
        [ScheduledTaskQueueName.ScheduledTasksQueueVehicleReRegistration]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
        [ScheduledTaskQueueName.ScheduledTasksQueueInvincibility]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
        [ScheduledTaskQueueName.ScheduledTasksQueueNotification]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
        [ScheduledTaskQueueName.ScheduledTasksQueueDocumentAcquirers]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
        [ScheduledTaskQueueName.ScheduledTasksQueueUser]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
        [ScheduledTaskQueueName.ScheduledTasksQueueAddress]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
        [ScheduledTaskQueueName.ScheduledTasksQueueDocumentDelivery]: {
            topics: [InternalTopic.TopicScheduledTasks],
        },
    },
}

// configuration for each topic: list of events the topic can publish messages
export const topicsConfig: TopicConfig = {
    [QueueConfigType.Internal]: {
        [InternalTopic.TopicScheduledTasks]: {
            events: Object.values(ScheduledTaskEvent),
        },
        [InternalTopic.TopicAuthUserSession]: {
            events: [
                InternalEvent.AuthCreateOrUpdateUserProfile,
                InternalEvent.AuthAssignUserToPushToken,
                InternalEvent.AuthUserLogOut,
                InternalEvent.AuthCreateOrUpdateEResidentProfile,
                InternalEvent.AuthAssignEResidentToPushToken,
                InternalEvent.AuthEResidentLogOut,
            ],
        },
        [InternalTopic.TopicDocumentsRegistry]: {
            events: [
                InternalEvent.DocumentsAddDocumentsInProfile,
                InternalEvent.DocumentsAddDocumentInProfile,
                InternalEvent.DocumentsAddDocumentPhoto,
                InternalEvent.DocumentsRemoveDocumentPhoto,
                InternalEvent.DocumentsAdultRegistrationAddressCommunity,
            ],
        },
        [InternalTopic.TopicGatewayUserActivity]: {
            events: [InternalEvent.GatewayUserActivity],
        },
        [InternalTopic.TopicPaymentDataLifeCycle]: {
            events: [
                InternalEvent.PaymentCallbackStatus,
                InternalEvent.PaymentCallbackStatusV2,
                InternalEvent.PaymentExecuted,
                InternalEvent.PaymentExpired,
            ],
        },
        [InternalTopic.TopicPublicServicePenaltiesLifeCycle]: {
            events: [InternalEvent.PublicServicePenaltyCreated],
        },
        [InternalTopic.TopicPublicServiceCriminalCertLifeCycle]: {
            events: [InternalEvent.PublicServiceCriminalCertificateStatusUpdated],
        },
        [InternalTopic.TopicCriminalCertLifeCycle]: {
            events: [InternalEvent.CriminalCertificateStatusUpdated],
        },
        [InternalTopic.TopicPublicServiceDebtsLifeCycle]: {
            events: [InternalEvent.PublicServiceReceivedOpenedDebt, InternalEvent.PublicServiceReceivedEnforcedDebt],
        },
        [InternalTopic.TopicPublicServiceSigningLifeCycle]: {
            events: [InternalEvent.PublicServiceSigningStatus],
        },
        [InternalTopic.TopicDocumentLifeCycle]: {
            events: [InternalEvent.DocumentsObtainedVehicleLicense, InternalEvent.DocumentsObtainedRefInternallyDisplacedPerson],
        },
        [InternalTopic.TopicUserSendMassNotifications]: {
            events: [
                InternalEvent.UserSendMassNotifications,
                InternalEvent.UserSendMassAnonymousNotifications,
                InternalEvent.UserSendMassSilentPushes,
            ],
        },
        [InternalTopic.TopicUserPenaltiesIdentification]: {
            events: [InternalEvent.UserPenaltyIdentified],
        },
        [InternalTopic.TopicUserProfileLifecycle]: {
            events: [InternalEvent.UserProfileCreated],
        },
        [InternalTopic.TopicNotificationLifeCycle]: {
            events: [
                InternalEvent.NotificationPenaltyCreated,
                InternalEvent.NotificationOpenedDebtCreated,
                InternalEvent.NotificationEnforcedDebtCreated,
                InternalEvent.NotificationHasRead,
                InternalEvent.NotificationHasDeleted,
            ],
        },
        [InternalTopic.TopicAcquirersOfferRequestLifeCycle]: {
            events: [
                InternalEvent.AcquirersOfferRequestHasDeleted,
                InternalEvent.AcquirersSharingStatus,
                InternalEvent.AcquirersSigningStatus,
            ],
        },
        [InternalTopic.TopicAnalytics]: {
            events: [InternalEvent.RateService],
        },
        [InternalTopic.TopicRating]: {
            events: [InternalEvent.RatingSaved],
        },
        [InternalTopic.TopicDocumentDeliveryLifeCycle]: {
            events: [InternalEvent.DocumentDeliveryCallbackStatus],
        },
    },
    [QueueConfigType.External]: {
        [ExternalTopic.Auth]: {
            events: [ExternalEvent.AuthSaveNfcScanResult, ExternalEvent.AuthGetInnByUnzr],
        },
        [ExternalTopic.FaceReco]: {
            events: [
                ExternalEvent.FaceRecoUserPhotoExtractFeaturePoints,
                ExternalEvent.FaceRecoUserPhotoMatch,
                ExternalEvent.FaceRecoAuthPhotoVerification,
                ExternalEvent.FaceRecoAuthNfcUserPersist,
            ],
        },
        [ExternalTopic.Notification]: {
            events: [
                ExternalEvent.NotificationSendEmail,
                ExternalEvent.NotificationSendSms,
                ExternalEvent.NotificationSendPush,
                ExternalEvent.NotificationPushTopicSubscribe,
                ExternalEvent.NotificationPushTopicUnsubscribe,
                ExternalEvent.NotificationSend,
                ExternalEvent.NotificationSendTarget,
                ExternalEvent.NotificationTopicSubscribe,
                ExternalEvent.NotificationTopicSubscribeTarget,
                ExternalEvent.NotificationTopicUnsubscribe,
            ],
        },
        [ExternalTopic.NotificationDistribution]: {
            events: [
                ExternalEvent.NotificationTemplateCreate,
                ExternalEvent.NotificationDistributionCreate,
                ExternalEvent.NotificationDistributionStatus,
                ExternalEvent.NotificationDistributionStatusRecipients,
                ExternalEvent.NotificationDistributionCancel,
            ],
        },
        [ExternalTopic.Repo]: {
            events: [
                ExternalEvent.RepoDocumentInternalPassport,
                ExternalEvent.RepoDocumentDriverLicense,
                ExternalEvent.RepoDocumentVehicleLicenses,
                ExternalEvent.RepoDocumentVehicleLicenseOwner,
                ExternalEvent.RepoDocumentVehicleLicenseProper,
                ExternalEvent.RepoDocumentVehicleInsurance,
                ExternalEvent.RepoDocumentStudentIdCard,
                ExternalEvent.RepoDocumentForeignPassport,
                ExternalEvent.RepoDocumentPassports,
                ExternalEvent.RepoDocumentPassportsByInn,
                ExternalEvent.RepoDocumentTaxpayerCard,
                ExternalEvent.RepoDocumentRefInternallyDisplacedPerson,
                ExternalEvent.RepoDocumentBirthCertificate,
                ExternalEvent.RepoAuthEisAgree,
                ExternalEvent.PublicServiceDrrpExtSearch,
                ExternalEvent.PublicServiceDrrpExtGroup,
                ExternalEvent.PublicServiceDrrpGetActualAtu,
                ExternalEvent.PublicServiceDriverLicenseExchangeApplication,
                ExternalEvent.PublicServiceDriverLicenseExchangePayment,
                ExternalEvent.PublicServiceInfotechDeliveryOrderCreate,
                ExternalEvent.PublicServiceInfotechDeliveryOrderOffertSend,
                ExternalEvent.PublicServiceGetPenaltiesByPeriod,
                ExternalEvent.PublicServiceGetPenaltiesFromInspectorByDrl,
                ExternalEvent.PublicServiceGetPenaltiesByVehicleLicense,
                ExternalEvent.PublicServiceGetPenaltyDetailsBySn,
                ExternalEvent.PublicServiceUpdatePenaltyPaymentStatus,
                ExternalEvent.PublicServiceUnemploymentStatusRegisterApplication,
                ExternalEvent.PublicServiceUnemploymentStatusApplicationStatus,
                ExternalEvent.PublicServiceUnemploymentBenefitsRegisterApplication,
                ExternalEvent.PublicServiceUnemploymentBenefitsApplicationStatus,
                ExternalEvent.PublicServiceUnemploymentStatusCancelingRegisterApplication,
                ExternalEvent.PublicServiceUnemploymentStatusCancelingApplicationStatus,
                ExternalEvent.RepoDmsUnitedTerritorialCommunitySendApplicationForRegistrationOfResidence,
                ExternalEvent.RepoDmsUnitedTerritorialCommunityResultApplicationForRegistrationOfResidence,
                ExternalEvent.PublicServiceInternallyDisplacedPersonConvertApplication,
                ExternalEvent.PublicServiceInternallyDisplacedPersonConvertApplications,
                ExternalEvent.PublicServiceInternallyDisplacedPersonDeconvertApplication,
                ExternalEvent.PublicServiceInternallyDisplacedPersonCheckApplication,
                ExternalEvent.PublicServiceInternallyDisplacedPersonDeconvertCheckApplication,
                ExternalEvent.PublicServiceInternallyDisplacedPersonCancel,
                ExternalEvent.PublicServiceInternallyDisplacedPersonChangeAddress,
                ExternalEvent.PublicServiceInternallyDisplacedApplicationResult,
                ExternalEvent.PublicServiceInternallyDisplacedPersonCancelProcessing,
                ExternalEvent.PublicServiceInternallyDisplacedPersonCancelResult,
                ExternalEvent.PublicServiceCriminalRecordCertOrder,
                ExternalEvent.PublicServiceCriminalRecordCertDownload,
                ExternalEvent.PublicServiceCriminalRecordCertOrderResult,
                ExternalEvent.AppealRequest,
                ExternalEvent.PublicServiceENotGetSignatories,
                ExternalEvent.PublicServiceENotGetSignature,
                ExternalEvent.PublicServiceENotGetDocument,
                ExternalEvent.PublicServiceHomecomingIdentityCardCreation,
                ExternalEvent.PublicServiceHomecomingIdentityCard,
                ExternalEvent.DocumentEducation,
                ExternalEvent.CheckUnzr,
                ExternalEvent.PublicServiceBondsAvailable,
                ExternalEvent.PublicServiceBondsDictionary,
                ExternalEvent.PublicServiceBondsProperty,
                ExternalEvent.PublicServiceBondsGetDocuments,
                ExternalEvent.PublicServiceBondsOrder,
                ExternalEvent.PublicServiceBondsStatements,
                ExternalEvent.PublicServiceBondsOrderCancel,
                ExternalEvent.PublicServiceResidenceCert,
                ExternalEvent.PublicServiceResidenceCertOrder,
                ExternalEvent.PublicServiceResidenceCertData,
                ExternalEvent.PublicServiceCourtCases,
                ExternalEvent.PublicServiceCourtCaseDetails,
                ExternalEvent.PublicServiceCourtDecisions,
                ExternalEvent.PublicServiceCourtDecisionDetails,
                ExternalEvent.PublicServiceCourtTrials,
                ExternalEvent.PublicServiceCourtTrialDetails,
                ExternalEvent.PublicServiceCourtPenalties,
                ExternalEvent.PublicServiceCourtPenaltyDetails,
                ExternalEvent.PublicServiceCourtPenaltyAddPayment,
                ExternalEvent.PublicServiceMortgageApplicationSend,
                ExternalEvent.PublicServiceMortgageApplicationStatus,
                ExternalEvent.GetAtuList,
                ExternalEvent.PublicServiceDebts,
                ExternalEvent.PublicServiceDebtsNotification,
                ExternalEvent.PublicServiceDebtsAddOnlinePayment,
                ExternalEvent.RepoDocumentRnokpp,
                ExternalEvent.GetArOfDeath,
                ExternalEvent.GetMarriageArByRnokpp,
                ExternalEvent.GetDivorceArByRnokpp,
                ExternalEvent.PublicServiceActNoteGetArByRnokpp,
                ExternalEvent.TemporaryOccupiedTerritories,
                ExternalEvent.RepoDocumentPensionCard,
                ExternalEvent.RepoDocumentCovidCertSign,
                ExternalEvent.RepoDocumentCovidCertVerify,
                ExternalEvent.RepoDocumentEPermit,
                ExternalEvent.PublicServiceReportMoneyAidPca,
                ExternalEvent.PublicServiceReportMoneyAidPpr,
                ExternalEvent.PublicServiceReportMoneyAidEnrollmentsUpdate,
                ExternalEvent.PublicServiceReportMortgageIssued,
                ExternalEvent.PublicServiceELightCheckAvailability,
                ExternalEvent.PublicServiceELightGetReportByDate,
                ExternalEvent.PublicServiceELightUploadOrdersList,
                ExternalEvent.PublicServiceUkrpostGetPostofficesByPostcodeCityid,
                ExternalEvent.PublicServiceProperUserAssignApplicationSend,
                ExternalEvent.PublicServiceProperUserCancelingApplicationSend,
                ExternalEvent.PublicServiceHscGetDictionary,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtSearchInfoMessageByRnokpp,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtUpdateInfoMessageAfterDrrp,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtUpdateInfoMessageOwnerChanged,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtAutomaticDiiaApplication,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtApplicationByDrrpIdRnokpp,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtApplicationFullInfo,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtApplicationStatusInfo,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtApplicationStatusInfoUpdate,
                ExternalEvent.PublicServiceDamagedPropertyExtSendInformationMessage,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaApplicationDestroyedSaving,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaApplicDuplicatesByOwnerCheck,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaCriminalRecordFileSaving,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaApplicationDestroyedFullInfoView,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaCoOwnerInformationMessageRead,
                ExternalEvent.PublicServiceCompensationDepositsApplicationSend,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificatesRead,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificateFullInfoRead,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificateExcerpt,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificateExcerptResult,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificateStatusRead,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaHousingCertificateStatusInfoUpdate,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaRepairCompletionMessageSaving,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaFundingRequestSaving,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaMonetaryCompensationRead,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaMonetaryCompensationFullInfoRead,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaMonetaryCompensationStatusInfoUpdate,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaConstructingStartMessageSaving,
                ExternalEvent.PublicServiceDamagedPropertyRecoveryExtTrembitaConstructingCompletionMessageSaving,
                ExternalEvent.PublicServiceCarReRegistrationExpertConclusion,
                ExternalEvent.PublicServiceCarReRegistrationClntAdd,
                ExternalEvent.PublicServiceCarReRegistrationLicensePlate,
                ExternalEvent.PublicServiceCarReRegistrationLicensePlateList,
                ExternalEvent.PublicServiceCarReRegistrationLicensePlateReservation,
                ExternalEvent.PublicServiceCarReRegistrationCancelPlateReservation,
                ExternalEvent.PublicServiceCarReRegistrationApplicationSend,
                ExternalEvent.PublicServiceCarReRegistrationCheckingResult,
                ExternalEvent.PublicServiceCarReRegistrationReceiptSend,
                ExternalEvent.PublicServiceCarReRegistrationCancel,
                ExternalEvent.PublicServiceDriverLicenseExchangeResult,
                ExternalEvent.PublicServiceInvincibilityShelters,
                ExternalEvent.PublicServiceInvincibilityPoints,
                ExternalEvent.PublicServiceInvincibilityPointsRating,
                ExternalEvent.PublicServiceInvincibilityPointsReviews,
                ExternalEvent.PublicServiceInvincibilityPointsAllReviews,
                ExternalEvent.PublicServiceDroneArmyRegisterApplication,
                ExternalEvent.PublicServiceNewsAction,
                ExternalEvent.PublicServiceNazkSendConfirmationProposals,
                ExternalEvent.PublicServiceNazkGetConfirmationResult,
            ],
        },
        [ExternalTopic.Attestation]: {
            events: [ExternalEvent.AttestationGoogleDevice, ExternalEvent.IntegrityGoogleDevice, ExternalEvent.AttestationHuaweiDevice],
        },
        [ExternalTopic.DiiaId]: {
            events: [
                ExternalEvent.DiiaIdCertificateCreate,
                ExternalEvent.DiiaIdCertificateRevoke,
                ExternalEvent.DiiaIdCertificateRevokeAll,
                ExternalEvent.DiiaIdHashFiles,
                ExternalEvent.DiiaIdSignHashesInit,
                ExternalEvent.DiiaIdHashFilesIntegrity,
                ExternalEvent.DiiaIdSignDpsPackageInit,
                ExternalEvent.DiiaIdSignDpsPackagePrepare,
                ExternalEvent.DiiaIdCertificateInfo,
            ],
        },
        [ExternalTopic.TaxCabinet]: {
            events: [
                ExternalEvent.PrivateEntrepreneurPayerCredentials,
                ExternalEvent.PrivateEntrepreneurBankAccounts,
                ExternalEvent.PrivateEntrepreneurTaxAccounts,
                ExternalEvent.PrivateEntrepreneurPayerDeclaration,
                ExternalEvent.PayerIncomeQuery,
                ExternalEvent.PayerIncomeAnswer,
            ],
        },
        [ExternalTopic.BankAccount]: {
            events: [
                ExternalEvent.PrivateEntrepreneurBankAccountIncomePeriod,
                ExternalEvent.PrivateEntrepreneurBankAccountReportPeriod,
                ExternalEvent.PublicServiceGetBanksByService,
                ExternalEvent.PublicServiceGetUserCardsByService,
            ],
        },
        [ExternalTopic.Vote]: {
            events: [
                ExternalEvent.VoteJoinPetitions,
                ExternalEvent.VoteJoinCommunity,
                ExternalEvent.VotePetitionAnswer,
                ExternalEvent.VotePetitionCategories,
                ExternalEvent.VotePetitionCreate,
                ExternalEvent.VotePetitionFollowers,
                ExternalEvent.VotePetitionInformation,
                ExternalEvent.VotePetitionSign,
                ExternalEvent.VotePetitionsSearch,

                ExternalEvent.VotePortalJoinCommunity,
                ExternalEvent.VotePortalPetitionAnswer,
                ExternalEvent.VotePortalPetitionCategories,
                ExternalEvent.VotePortalPetitionCreate,
                ExternalEvent.VotePortalPetitionFollowers,
                ExternalEvent.VotePortalPetitionInformation,
                ExternalEvent.VotePortalPetitionSign,
                ExternalEvent.VotePortalPetitionsSearch,

                ExternalEvent.VoteBackstagePetitionAdminCommunitiesList,
                ExternalEvent.VoteBackstagePetitionAdminCommunity,
                ExternalEvent.VoteBackstagePetitionAdminCommunityUpdate,
                ExternalEvent.VoteBackstagePetitionAdminCommunityCreate,
                ExternalEvent.VoteBackstagePetitionAdminStatistic,
                ExternalEvent.VoteBackstagePetitionAdminUsers,
                ExternalEvent.VoteBackstagePetitionAdminUserPetitions,

                ExternalEvent.VoteBackstagePetitionsSearch,
                ExternalEvent.VoteBackstagePetitionInformation,
                ExternalEvent.VoteBackstagePetitionUpdate,
                ExternalEvent.VoteBackstagePetitionUserInfo,
                ExternalEvent.VoteBackstagePetitionCommunityStatistic,
                ExternalEvent.VoteBackstageCommunityInfo,
            ],
        },
        [ExternalTopic.Poll]: {
            events: [
                ExternalEvent.VotePollList,
                ExternalEvent.VotePollDetails,
                ExternalEvent.VotePollSubmit,
                ExternalEvent.VoteBackstagePollCreate,
                ExternalEvent.VoteBackstagePollUpdate,
                ExternalEvent.VoteBackstagePollClose,
                ExternalEvent.VoteBackstagePollPublish,
                ExternalEvent.VoteBackstagePollList,
                ExternalEvent.VoteBackstagePollDetails,
                ExternalEvent.VoteBackstagePollHistory,
                ExternalEvent.VoteBackstagePollLaunch,
                ExternalEvent.VoteBackstagePollResults,
                ExternalEvent.VoteBackstagePollUserAdd,
            ],
        },
        [ExternalTopic.Medical]: {
            events: [ExternalEvent.MedicalDataTransfer, ExternalEvent.MedicalDataTransferResult],
        },
        [ExternalTopic.Document]: {
            events: [
                ExternalEvent.DocumentCovidCertificateProcessing,
                ExternalEvent.DocumentCovidCertificate,
                ExternalEvent.DocumentResidenceCertProcessing,
                ExternalEvent.DocumentResidenceCert,
            ],
        },
        [ExternalTopic.DgcValidator]: {
            events: [ExternalEvent.DgcValidate],
        },
        [ExternalTopic.Ubki]: {
            events: [ExternalEvent.UbkiCreditInfo],
        },
        [ExternalTopic.Pfu]: {
            events: [
                ExternalEvent.PensionFundPfuAuth,
                ExternalEvent.PensionFundGeneralPersonData,
                ExternalEvent.PensionFundPersonInsuredData,
                ExternalEvent.PensionFundPensionCardData,
                ExternalEvent.PensionFundInitExternalSession,
            ],
        },
        [ExternalTopic.Aid]: {
            events: [ExternalEvent.AidVaccinationStatus],
        },
        [ExternalTopic.AcquirerSharing]: {
            events: [ExternalEvent.AcquirerDocumentRequest, ExternalEvent.AcquirerDocumentResponse],
        },
        [ExternalTopic.Delta]: {
            events: [ExternalEvent.DeltaShareObjects],
        },
        [ExternalTopic.EResident]: {
            events: [ExternalEvent.EResidentDocuments, ExternalEvent.EResidentAuthConfirmation, ExternalEvent.EResidentDiiaIdCreation],
        },
        [ExternalTopic.User]: {
            events: [ExternalEvent.UserGetInfoForFilters],
        },
        [ExternalTopic.SuperGen]: {
            events: [ExternalEvent.SuperGenGeneratePdfDocument],
        },
        [ExternalTopic.Office]: {
            events: [
                ExternalEvent.OfficeIdentifier,
                ExternalEvent.OfficeProfileMy,
                ExternalEvent.OfficeProfileDetails,
                ExternalEvent.OfficeSearchFields,
                ExternalEvent.OfficeSearchFacets,
                ExternalEvent.OfficeSearchPeople,
                ExternalEvent.OfficeSearchAutocomplete,
                ExternalEvent.OfficeBadgeAvailable,
                ExternalEvent.OfficeBadgeDetails,
                ExternalEvent.OfficeBadgeProfileList,
                ExternalEvent.OfficeBadgeProfileGive,
                ExternalEvent.OfficePhoto,
                ExternalEvent.OfficeIdentifierRemoved,
                ExternalEvent.OfficeIdentifierTokenFail,
            ],
        },
        [ExternalTopic.OfficePoll]: {
            events: [
                ExternalEvent.OfficePollCreateAndPublish,
                ExternalEvent.OfficePollGet,
                ExternalEvent.OfficePollOnboarding,
                ExternalEvent.OfficePollDelete,
                ExternalEvent.OfficePollCount,
            ],
        },
        [ExternalTopic.NotificationCampaign]: {
            events: [
                ExternalEvent.NotificationCampaignStatusReady,
                ExternalEvent.NotificationCampaignCreate,
                ExternalEvent.NotificationCampaignJoinUsers,
                ExternalEvent.NotificationCampaignSendMessage,
            ],
        },
    },
}
